# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 6


work:
  mass: 3.463388126201571
  lr: 0.17145
  lf: 0.15597534362552312
  tlad: 4 #0.82461887897713965
  # Lookahead points
  nlad: 10
  vgain: 1.5 #0.90338203837889

    

map1:
  # map paths
  map_path: 'maps/map0' #'./example_map' #
  # raceline path and indices
  wpt_path: 'centerlines/map0.csv' #./example_waypoints.csv'
  map_ext: '.png'
  # starting pose for map
  #sx: 0.7
  #sy: 0.0
  #stheta: 1.37079632679
  wpt_delim: ','
  wpt_rowskip: 1 #3
  wpt_xind: 0 #1
  wpt_yind: 1 #2
  wpt_thind: 3
  wpt_vind: 5


  bpt_path: 'borderlines/map0.csv' #./example_waypoints.csv'
  bpt_delim: ','
  bpt_rowskip: 1 #3
  bpt_xind: 0 #1
  bpt_yind: 1 #2
  bpt_thind: 3
  bpt_vind: 5



map2:
  # map paths
  map_path: 'maps/map1' #'./example_map' #
  # raceline path and indices
  wpt_path: 'centerlines/map1.csv' #./example_waypoints.csv'
  map_ext: '.png'
  # starting pose for map
  #sx: 0.7
  #sy: 0.0
  #stheta: 1.37079632679
  wpt_delim: ','
  wpt_rowskip: 1 #3
  wpt_xind: 0 #1
  wpt_yind: 1 #2
  wpt_thind: 3
  wpt_vind: 5



  bpt_path: 'borderlines/map1.csv' #./example_waypoints.csv'
  bpt_delim: ','
  bpt_rowskip: 1 #3
  bpt_xind: 0 #1
  bpt_yind: 1 #2
  bpt_thind: 3
  bpt_vind: 5


map3:
  # map paths
  map_path: 'maps/map2' #'./example_map' #
  # raceline path and indices
  wpt_path: 'centerlines/map2.csv' #./example_waypoints.csv'
  map_ext: '.png'
  # starting pose for map
  #sx: 0.7
  #sy: 0.0
  #stheta: 1.37079632679
  wpt_delim: ','
  wpt_rowskip: 1 #3
  wpt_xind: 0 #1
  wpt_yind: 1 #2
  wpt_thind: 3
  wpt_vind: 5



  bpt_path: 'borderlines/map2.csv' #./example_waypoints.csv'
  bpt_delim: ','
  bpt_rowskip: 1 #3
  bpt_xind: 0 #1
  bpt_yind: 1 #2
  bpt_thind: 3
  bpt_vind: 5

map4:
  # map paths
  map_path: 'maps/map3' #'./example_map' #
  # raceline path and indices
  wpt_path: 'centerlines/map3.csv' #./example_waypoints.csv'
  map_ext: '.png'
  # starting pose for map
  #sx: 0.7
  #sy: 0.0
  #stheta: 1.37079632679
  wpt_delim: ','
  wpt_rowskip: 1 #3
  wpt_xind: 0 #1
  wpt_yind: 1 #2
  wpt_thind: 3
  wpt_vind: 5



  bpt_path: 'borderlines/map3.csv' #./example_waypoints.csv'
  bpt_delim: ','
  bpt_rowskip: 1 #3
  bpt_xind: 0 #1
  bpt_yind: 1 #2
  bpt_thind: 3
  bpt_vind: 5


map5:
  # map paths
  map_path: 'maps/map4' #'./example_map' #
  # raceline path and indices
  wpt_path: 'centerlines/map4.csv' #./example_waypoints.csv'
  map_ext: '.png'
  # starting pose for map
  #sx: 0.7
  #sy: 0.0
  #stheta: 1.37079632679
  wpt_delim: ','
  wpt_rowskip: 1 #3
  wpt_xind: 0 #1
  wpt_yind: 1 #2
  wpt_thind: 3
  wpt_vind: 5


  bpt_path: 'borderlines/map4.csv' #./example_waypoints.csv'
  bpt_delim: ','
  bpt_rowskip: 1 #3
  bpt_xind: 0 #1
  bpt_yind: 1 #2
  bpt_thind: 3
  bpt_vind: 5





# starting pose for map
#sx: 0.7
#sy: 0.0
#stheta: 1.37079632679

 

# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345
